#!/usr/bin/env ruby

$:.unshift File.dirname(__FILE__)

require "common"

if ARGV[0] == "all"
  %w[
    benchmark-memcached-mget
    benchmark-redis-mget
    benchmark-redis 
    benchmark-memcached
    benchmark-redis-pipelined 
  ].each { |file| require file }
else
  require ARGV[0]
end
